/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;
import Gestores.GestorCuestionario;
import java.util.List;
import Entidades.*;
import java.util.ArrayList;


/**
 *
 * @author John
 */
public class CompletarQuest extends javax.swing.JFrame {

    /**
     * Creates new form Pantallak
     */
    public CompletarQuest() {
        initComponents();
        setSize(1024, 768);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        arriba = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        candidatoName = new javax.swing.JLabel();
        candidatoDNI = new javax.swing.JLabel();
        abajo = new javax.swing.JPanel();
        volverBtn = new javax.swing.JButton();
        centro = new javax.swing.JPanel();
        centroInterior = new javax.swing.JPanel();
        arribaInterior = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        izquierda = new javax.swing.JPanel();
        derecha = new javax.swing.JPanel();
        abajoInterior = new javax.swing.JPanel();
        aceptarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        instrucciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondo.setLayout(new java.awt.BorderLayout(10, 10));

        arriba.setBorder(new javax.swing.border.MatteBorder(null));
        arriba.setPreferredSize(new java.awt.Dimension(1024, 100));
        arriba.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cuestionario");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        arriba.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1030, 60));

        candidatoName.setText("Candidato:");
        arriba.add(candidatoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 420, 20));

        candidatoDNI.setText("DNI:");
        arriba.add(candidatoDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 470, 20));

        fondo.add(arriba, java.awt.BorderLayout.PAGE_START);

        abajo.setBorder(new javax.swing.border.MatteBorder(null));

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abajoLayout = new javax.swing.GroupLayout(abajo);
        abajo.setLayout(abajoLayout);
        abajoLayout.setHorizontalGroup(
            abajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abajoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(volverBtn)
                .addContainerGap(901, Short.MAX_VALUE))
        );
        abajoLayout.setVerticalGroup(
            abajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abajoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volverBtn)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        fondo.add(abajo, java.awt.BorderLayout.PAGE_END);

        centro.setBorder(new javax.swing.border.MatteBorder(null));
        centro.setLayout(new java.awt.BorderLayout(10, 10));

        centroInterior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51), 2));
        centroInterior.setLayout(new java.awt.BorderLayout(10, 10));

        arribaInterior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Instrucciones");

        javax.swing.GroupLayout arribaInteriorLayout = new javax.swing.GroupLayout(arribaInterior);
        arribaInterior.setLayout(arribaInteriorLayout);
        arribaInteriorLayout.setHorizontalGroup(
            arribaInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, arribaInteriorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        arribaInteriorLayout.setVerticalGroup(
            arribaInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arribaInteriorLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        centroInterior.add(arribaInterior, java.awt.BorderLayout.PAGE_START);

        izquierda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        javax.swing.GroupLayout izquierdaLayout = new javax.swing.GroupLayout(izquierda);
        izquierda.setLayout(izquierdaLayout);
        izquierdaLayout.setHorizontalGroup(
            izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        izquierdaLayout.setVerticalGroup(
            izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        centroInterior.add(izquierda, java.awt.BorderLayout.LINE_START);

        derecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        javax.swing.GroupLayout derechaLayout = new javax.swing.GroupLayout(derecha);
        derecha.setLayout(derechaLayout);
        derechaLayout.setHorizontalGroup(
            derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        derechaLayout.setVerticalGroup(
            derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        centroInterior.add(derecha, java.awt.BorderLayout.LINE_END);

        abajoInterior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        aceptarBtn.setText("aceptar");
        aceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("cancelar");

        javax.swing.GroupLayout abajoInteriorLayout = new javax.swing.GroupLayout(abajoInterior);
        abajoInterior.setLayout(abajoInteriorLayout);
        abajoInteriorLayout.setHorizontalGroup(
            abajoInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abajoInteriorLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(aceptarBtn)
                .addGap(297, 297, 297)
                .addComponent(cancelarBtn)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        abajoInteriorLayout.setVerticalGroup(
            abajoInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abajoInteriorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(abajoInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarBtn)
                    .addComponent(cancelarBtn))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        centroInterior.add(abajoInterior, java.awt.BorderLayout.PAGE_END);

        instrucciones.setEditable(false);
        instrucciones.setColumns(20);
        instrucciones.setRows(5);
        jScrollPane1.setViewportView(instrucciones);

        centroInterior.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        centro.add(centroInterior, java.awt.BorderLayout.CENTER);

        fondo.add(centro, java.awt.BorderLayout.CENTER);

        getContentPane().add(fondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Carga Candidato
    
    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnActionPerformed
        
        
    }//GEN-LAST:event_aceptarBtnActionPerformed
    public void cargaCuestionario(){
        // Carga Candidato:
        
        GestorCuestionario gestorCuestionario = GestorCuestionario.getInstance();
        List cueList = null;
        Cuestionario s;
        cueList = gestorCuestionario.findQuest();
        
        s = (Cuestionario) cueList.get(0);
        
       
        
        candidatoName.setText("Candidato: " + s.getCandidato().getNombreApellido());
        candidatoDNI.setText("DNI: "+ s.getCandidato().getNumeroDocumento().toString());
    
    }
    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompletarQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompletarQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompletarQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompletarQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompletarQuest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abajo;
    private javax.swing.JPanel abajoInterior;
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JPanel arriba;
    private javax.swing.JPanel arribaInterior;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JLabel candidatoDNI;
    private javax.swing.JLabel candidatoName;
    private javax.swing.JPanel centro;
    private javax.swing.JPanel centroInterior;
    private javax.swing.JPanel derecha;
    private javax.swing.JPanel fondo;
    private javax.swing.JTextArea instrucciones;
    private javax.swing.JPanel izquierda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
