package Entidades;
// Generated 14/11/2016 15:56:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Competencia generated by hbm2java
 */
public class Competencia  implements java.io.Serializable {


     private int idCompetencia;
     private String nombreCompetencia;
     private String descripcion;
     private Boolean eliminado;
     private Set puestoCompetencias = new HashSet(0);

    public Competencia() {
    }

	
    public Competencia(int idCompetencia) {
        this.idCompetencia = idCompetencia;
    }
    public Competencia(int idCompetencia, String nombreCompetencia, String descripcion, Boolean eliminado, Set puestoCompetencias) {
       this.idCompetencia = idCompetencia;
       this.nombreCompetencia = nombreCompetencia;
       this.descripcion = descripcion;
       this.eliminado = eliminado;
       this.puestoCompetencias = puestoCompetencias;
    }
   
    public int getIdCompetencia() {
        return this.idCompetencia;
    }
    
    public void setIdCompetencia(int idCompetencia) {
        this.idCompetencia = idCompetencia;
    }
    public String getNombreCompetencia() {
        return this.nombreCompetencia;
    }
    
    public void setNombreCompetencia(String nombreCompetencia) {
        this.nombreCompetencia = nombreCompetencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEliminado() {
        return this.eliminado;
    }
    
    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }
    public Set getPuestoCompetencias() {
        return this.puestoCompetencias;
    }
    
    public void setPuestoCompetencias(Set puestoCompetencias) {
        this.puestoCompetencias = puestoCompetencias;
    }




}


