package Entidades;
// Generated 06-dic-2016 15:03:43 by Hibernate Tools 4.3.1



/**
 * Configuracion generated by hbm2java
 */
public class Configuracion  implements java.io.Serializable {


     private int idConfiguracion;
     private String instrucciones;
     private Integer cantidadMaximaAccesos;
     private Integer preguntasPorBloque;
     private Integer tiempoMaximoCuestionario;
     private Integer tiempoMaximoCuestionarioActivo;

    public Configuracion() {
    }

    
    public Configuracion(int idConfiguracion) {
        this.idConfiguracion = idConfiguracion;
    }  
    public Configuracion(int idConfiguracion, String instrucciones, Integer cantidadMaximaAccesos, Integer preguntasPorBloque, Integer tiempoMaximoCuestionario, Integer tiempoMaximoCuestionarioActivo) {
       this.idConfiguracion = idConfiguracion;
       this.instrucciones = instrucciones;
       this.cantidadMaximaAccesos = cantidadMaximaAccesos;
       this.preguntasPorBloque = preguntasPorBloque;
       this.tiempoMaximoCuestionario = tiempoMaximoCuestionario;
       this.tiempoMaximoCuestionarioActivo = tiempoMaximoCuestionarioActivo;
    }
   
    public int getIdConfiguracion() {
        return this.idConfiguracion;
    }
    
    public void setIdConfiguracion(int idConfiguracion) {
        this.idConfiguracion = idConfiguracion;
    }
    public String getInstrucciones() {
        return this.instrucciones;
    }
    
    public void setInstrucciones(String instrucciones) {
        this.instrucciones = instrucciones;
    }
    public Integer getCantidadMaximaAccesos() {
        return this.cantidadMaximaAccesos;
    }
    
    public void setCantidadMaximaAccesos(Integer cantidadMaximaAccesos) {
        this.cantidadMaximaAccesos = cantidadMaximaAccesos;
    }
    public Integer getPreguntasPorBloque() {
        return this.preguntasPorBloque;
    }
    
    public void setPreguntasPorBloque(Integer preguntasPorBloque) {
        this.preguntasPorBloque = preguntasPorBloque;
    }
    public Integer getTiempoMaximoCuestionario() {
        return this.tiempoMaximoCuestionario;
    }
    
    public void setTiempoMaximoCuestionario(Integer tiempoMaximoCuestionario) {
        this.tiempoMaximoCuestionario = tiempoMaximoCuestionario;
    }
    public Integer getTiempoMaximoCuestionarioActivo() {
        return this.tiempoMaximoCuestionarioActivo;
    }
    
    public void setTiempoMaximoCuestionarioActivo(Integer tiempoMaximoCuestionarioActivo) {
        this.tiempoMaximoCuestionarioActivo = tiempoMaximoCuestionarioActivo;
    }




}


