package Entidades;
// Generated 16/09/2016 18:42:16 by Hibernate Tools 4.3.1



/**
 * Consultor generated by hbm2java
 */
public class Consultor  implements java.io.Serializable {


     private int idConsultor;
     private String username;
     private String clave;
     private String nombre;

    public Consultor() {
    }

	
    public Consultor(int idConsultor, String username, String clave) {
        this.idConsultor = idConsultor;
        this.username = username;
        this.clave = clave;
    }
    public Consultor(int idConsultor, String username, String clave, String nombre) {
       this.idConsultor = idConsultor;
       this.username = username;
       this.clave = clave;
       this.nombre = nombre;
    }
   
    public int getIdConsultor() {
        return this.idConsultor;
    }
    
    public void setIdConsultor(int idConsultor) {
        this.idConsultor = idConsultor;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


