package Entidades;
// Generated 06-dic-2016 15:03:43 by Hibernate Tools 4.3.1



/**
 * CuestionarioRespuestaCopia generated by hbm2java
 */
public class CuestionarioRespuestaCopia  implements java.io.Serializable {


     private CuestionarioRespuestaCopiaId id;
     private Cuestionario cuestionario;
     private RespuestaCopia respuestaCopia;
     private Integer orden;

    public CuestionarioRespuestaCopia() {
    }

	
    public CuestionarioRespuestaCopia(CuestionarioRespuestaCopiaId id, Cuestionario cuestionario, RespuestaCopia respuestaCopia) {
        this.id = id;
        this.cuestionario = cuestionario;
        this.respuestaCopia = respuestaCopia;
    }
    public CuestionarioRespuestaCopia(CuestionarioRespuestaCopiaId id, Cuestionario cuestionario, RespuestaCopia respuestaCopia, Integer orden) {
       this.id = id;
       this.cuestionario = cuestionario;
       this.respuestaCopia = respuestaCopia;
       this.orden = orden;
    }
   
    public CuestionarioRespuestaCopiaId getId() {
        return this.id;
    }
    
    public void setId(CuestionarioRespuestaCopiaId id) {
        this.id = id;
    }
    public Cuestionario getCuestionario() {
        return this.cuestionario;
    }
    
    public void setCuestionario(Cuestionario cuestionario) {
        this.cuestionario = cuestionario;
    }
    public RespuestaCopia getRespuestaCopia() {
        return this.respuestaCopia;
    }
    
    public void setRespuestaCopia(RespuestaCopia respuestaCopia) {
        this.respuestaCopia = respuestaCopia;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }




}


