package Entidades;
// Generated 06-dic-2016 15:03:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Factor generated by hbm2java
 */
public class Factor  implements java.io.Serializable {


     private int idFactor;
     private Competencia competencia;
     private String nombre;
     private String descripcion;
     private Integer numeroOrden;
     private Boolean eliminado;
     private Set<Pregunta> preguntas = new HashSet<Pregunta>(0);
     private Set<RaEliminacion> raEliminacions = new HashSet<RaEliminacion>(0);

    public Factor() {
    }

	
    public Factor(int idFactor) {
        this.idFactor = idFactor;
    }
    public Factor(int idFactor, Competencia competencia, String nombre, String descripcion, Integer numeroOrden, Boolean eliminado, Set<Pregunta> preguntas, Set<RaEliminacion> raEliminacions) {
       this.idFactor = idFactor;
       this.competencia = competencia;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.numeroOrden = numeroOrden;
       this.eliminado = eliminado;
       this.preguntas = preguntas;
       this.raEliminacions = raEliminacions;
    }
   
    public int getIdFactor() {
        return this.idFactor;
    }
    
    public void setIdFactor(int idFactor) {
        this.idFactor = idFactor;
    }
    public Competencia getCompetencia() {
        return this.competencia;
    }
    
    public void setCompetencia(Competencia competencia) {
        this.competencia = competencia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getNumeroOrden() {
        return this.numeroOrden;
    }
    
    public void setNumeroOrden(Integer numeroOrden) {
        this.numeroOrden = numeroOrden;
    }
    public Boolean getEliminado() {
        return this.eliminado;
    }
    
    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }
    public Set<Pregunta> getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set<Pregunta> preguntas) {
        this.preguntas = preguntas;
    }
    public Set<RaEliminacion> getRaEliminacions() {
        return this.raEliminacions;
    }
    
    public void setRaEliminacions(Set<RaEliminacion> raEliminacions) {
        this.raEliminacions = raEliminacions;
    }




}


