package Entidades;
// Generated 06-dic-2016 15:03:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * OpcionRespuesta generated by hbm2java
 */
public class OpcionRespuesta  implements java.io.Serializable {


     private int idOpcionRespuesta;
     private String nombreOpcionRespuesta;
     private String descripcion;
     private Boolean eliminado;
     private Set<RaEliminacion> raEliminacions = new HashSet<RaEliminacion>(0);
     private Set<Respuesta> respuestas = new HashSet<Respuesta>(0);
     private Set<Pregunta> preguntas = new HashSet<Pregunta>(0);

    public OpcionRespuesta() {
    }

	
    public OpcionRespuesta(int idOpcionRespuesta) {
        this.idOpcionRespuesta = idOpcionRespuesta;
    }
    public OpcionRespuesta(int idOpcionRespuesta, String nombreOpcionRespuesta, String descripcion, Boolean eliminado, Set<RaEliminacion> raEliminacions, Set<Respuesta> respuestas, Set<Pregunta> preguntas) {
       this.idOpcionRespuesta = idOpcionRespuesta;
       this.nombreOpcionRespuesta = nombreOpcionRespuesta;
       this.descripcion = descripcion;
       this.eliminado = eliminado;
       this.raEliminacions = raEliminacions;
       this.respuestas = respuestas;
       this.preguntas = preguntas;
    }
   
    public int getIdOpcionRespuesta() {
        return this.idOpcionRespuesta;
    }
    
    public void setIdOpcionRespuesta(int idOpcionRespuesta) {
        this.idOpcionRespuesta = idOpcionRespuesta;
    }
    public String getNombreOpcionRespuesta() {
        return this.nombreOpcionRespuesta;
    }
    
    public void setNombreOpcionRespuesta(String nombreOpcionRespuesta) {
        this.nombreOpcionRespuesta = nombreOpcionRespuesta;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEliminado() {
        return this.eliminado;
    }
    
    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }
    public Set<RaEliminacion> getRaEliminacions() {
        return this.raEliminacions;
    }
    
    public void setRaEliminacions(Set<RaEliminacion> raEliminacions) {
        this.raEliminacions = raEliminacions;
    }
    public Set<Respuesta> getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set<Respuesta> respuestas) {
        this.respuestas = respuestas;
    }
    public Set<Pregunta> getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set<Pregunta> preguntas) {
        this.preguntas = preguntas;
    }




}


