package Entidades;
// Generated 06-dic-2016 15:03:43 by Hibernate Tools 4.3.1



/**
 * PonderaCopia generated by hbm2java
 */
public class PonderaCopia  implements java.io.Serializable {


     private int idPreguntaCopia;
     private int idRespuestaCopia;
     private PreguntaCopia preguntaCopia;
     private RespuestaCopia respuestaCopia;
     private Integer ponderacion;

    public PonderaCopia() {
    }

	
    public PonderaCopia(int idPreguntaCopia, int idRespuestaCopia, PreguntaCopia preguntaCopia, RespuestaCopia respuestaCopia) {
        this.idPreguntaCopia = idPreguntaCopia;
        this.idRespuestaCopia = idRespuestaCopia;
        this.preguntaCopia = preguntaCopia;
        this.respuestaCopia = respuestaCopia;
    }
    public PonderaCopia(int idPreguntaCopia, int idRespuestaCopia, PreguntaCopia preguntaCopia, RespuestaCopia respuestaCopia, Integer ponderacion) {
       this.idPreguntaCopia = idPreguntaCopia;
        this.idRespuestaCopia = idRespuestaCopia;
       this.preguntaCopia = preguntaCopia;
       this.respuestaCopia = respuestaCopia;
       this.ponderacion = ponderacion;
    }
   
    public int getIdPreguntaCopia() {
        return this.idPreguntaCopia;
    }
    
    public void setIdPreguntaCopia(int idPreguntaCopia) {
        this.idPreguntaCopia = idPreguntaCopia;
    }
    public int getIdRespuestaCopia() {
        return this.idRespuestaCopia;
    }
    
    public void setIdRespuestaCopia(int idRespuestaCopia) {
        this.idRespuestaCopia = idRespuestaCopia;
    }
    
    public void setPreguntaCopia(PreguntaCopia preguntaCopia) {
        this.preguntaCopia = preguntaCopia;
    }
    public RespuestaCopia getRespuestaCopia() {
        return this.respuestaCopia;
    }
    
    public void setRespuestaCopia(RespuestaCopia respuestaCopia) {
        this.respuestaCopia = respuestaCopia;
    }
    
     public RespuestaCopia getPreguntaCopia() {
        return this.respuestaCopia;
    }
    public Integer getPonderacion() {
        return this.ponderacion;
    }
    
    public void setPonderacion(Integer ponderacion) {
        this.ponderacion = ponderacion;
    }




}


