package Entidades;
// Generated 06-dic-2016 15:03:43 by Hibernate Tools 4.3.1



/**
 * Pondera generated by hbm2java
 */
public class Pondera  implements java.io.Serializable {


     private int idPregunta;
     private int idRespuesta;
     private Pregunta pregunta;
     private Respuesta respuesta;
     private Integer ponderacion;

    public Pondera() {
    }

	
    public Pondera(int idPregunta, int idRespuesta, Pregunta pregunta, Respuesta respuesta) {
        this.idPregunta = idPregunta;
        this.idRespuesta = idRespuesta;
        this.pregunta = pregunta;
        this.respuesta = respuesta;
    }
    public Pondera(int idPregunta, int idRespuesta, Pregunta pregunta, Respuesta respuesta, Integer ponderacion) {
       this.idPregunta = idPregunta;
       this.idRespuesta = idRespuesta;
       this.pregunta = pregunta;
       this.respuesta = respuesta;
       this.ponderacion = ponderacion;
    }
   
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public int getIdRespuesta() {
        return this.idRespuesta;
    }
    
    public void setIdRespuesta(int idRespuesta) {
        this.idRespuesta = idRespuesta;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Respuesta getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(Respuesta respuesta) {
        this.respuesta = respuesta;
    }
    public Integer getPonderacion() {
        return this.ponderacion;
    }
    
    public void setPonderacion(Integer ponderacion) {
        this.ponderacion = ponderacion;
    }




}


