package Entidades;
// Generated 06-dic-2016 15:03:43 by Hibernate Tools 4.3.1



/**
 * PonderaCopia generated by hbm2java
 */
public class PonderaCopia  implements java.io.Serializable {


     private PonderaCopiaId id;
     private PreguntaCopia preguntaCopia;
     private RespuestaCopia respuestaCopia;
     private Integer ponderacion;

    public PonderaCopia() {
    }

	
    public PonderaCopia(PonderaCopiaId id, PreguntaCopia preguntaCopia, RespuestaCopia respuestaCopia) {
        this.id = id;
        this.preguntaCopia = preguntaCopia;
        this.respuestaCopia = respuestaCopia;
    }
    public PonderaCopia(PonderaCopiaId id, PreguntaCopia preguntaCopia, RespuestaCopia respuestaCopia, Integer ponderacion) {
       this.id = id;
       this.preguntaCopia = preguntaCopia;
       this.respuestaCopia = respuestaCopia;
       this.ponderacion = ponderacion;
    }
   
    public PonderaCopiaId getId() {
        return this.id;
    }
    
    public void setId(PonderaCopiaId id) {
        this.id = id;
    }
    public PreguntaCopia getPreguntaCopia() {
        return this.preguntaCopia;
    }
    
    public void setPreguntaCopia(PreguntaCopia preguntaCopia) {
        this.preguntaCopia = preguntaCopia;
    }
    public RespuestaCopia getRespuestaCopia() {
        return this.respuestaCopia;
    }
    
    public void setRespuestaCopia(RespuestaCopia respuestaCopia) {
        this.respuestaCopia = respuestaCopia;
    }
    public Integer getPonderacion() {
        return this.ponderacion;
    }
    
    public void setPonderacion(Integer ponderacion) {
        this.ponderacion = ponderacion;
    }




}


