package Entidades;
// Generated 06-dic-2016 15:03:43 by Hibernate Tools 4.3.1



/**
 * Pondera generated by hbm2java
 */
public class Pondera  implements java.io.Serializable {


     private PonderaId id;
     private Pregunta pregunta;
     private Respuesta respuesta;
     private Integer ponderacion;

    public Pondera() {
    }

	
    public Pondera(PonderaId id, Pregunta pregunta, Respuesta respuesta) {
        this.id = id;
        this.pregunta = pregunta;
        this.respuesta = respuesta;
    }
    public Pondera(PonderaId id, Pregunta pregunta, Respuesta respuesta, Integer ponderacion) {
       this.id = id;
       this.pregunta = pregunta;
       this.respuesta = respuesta;
       this.ponderacion = ponderacion;
    }
   
    public PonderaId getId() {
        return this.id;
    }
    
    public void setId(PonderaId id) {
        this.id = id;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Respuesta getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(Respuesta respuesta) {
        this.respuesta = respuesta;
    }
    public Integer getPonderacion() {
        return this.ponderacion;
    }
    
    public void setPonderacion(Integer ponderacion) {
        this.ponderacion = ponderacion;
    }




}


