package Entidades;
// Generated 06-dic-2016 15:03:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private int idPregunta;
     private Factor factor;
     private OpcionRespuesta opcionRespuesta;
     private String nombrePregunta;
     private String pregunta;
     private String descripcion;
     private Set<RaEliminacion> raEliminacions = new HashSet<RaEliminacion>(0);
     private Set<Pondera> ponderas = new HashSet<Pondera>(0);

    public Pregunta() {
    }

	
    public Pregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public Pregunta(int idPregunta, Factor factor, OpcionRespuesta opcionRespuesta, String nombrePregunta, String pregunta, String descripcion, Set<RaEliminacion> raEliminacions, Set<Pondera> ponderas) {
       this.idPregunta = idPregunta;
       this.factor = factor;
       this.opcionRespuesta = opcionRespuesta;
       this.nombrePregunta = nombrePregunta;
       this.pregunta = pregunta;
       this.descripcion = descripcion;
       this.raEliminacions = raEliminacions;
       this.ponderas = ponderas;
    }
   
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public Factor getFactor() {
        return this.factor;
    }
    
    public void setFactor(Factor factor) {
        this.factor = factor;
    }
    public OpcionRespuesta getOpcionRespuesta() {
        return this.opcionRespuesta;
    }
    
    public void setOpcionRespuesta(OpcionRespuesta opcionRespuesta) {
        this.opcionRespuesta = opcionRespuesta;
    }
    public String getNombrePregunta() {
        return this.nombrePregunta;
    }
    
    public void setNombrePregunta(String nombrePregunta) {
        this.nombrePregunta = nombrePregunta;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<RaEliminacion> getRaEliminacions() {
        return this.raEliminacions;
    }
    
    public void setRaEliminacions(Set<RaEliminacion> raEliminacions) {
        this.raEliminacions = raEliminacions;
    }
    public Set<Pondera> getPonderas() {
        return this.ponderas;
    }
    
    public void setPonderas(Set<Pondera> ponderas) {
        this.ponderas = ponderas;
    }




}


