package Entidades;
// Generated 06-dic-2016 15:03:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PreguntaCopia generated by hbm2java
 */
public class PreguntaCopia  implements java.io.Serializable {


     private int idPreguntaCopia;
     private FactorCopia factorCopia;
     private OpcionRespuestaCopia opcionRespuestaCopia;
     private String nombrePregunta;
     private String pregunta;
     private String descripcion;
     private Set<CuestionarioPreguntaCopia> cuestionarioPreguntaCopias = new HashSet<CuestionarioPreguntaCopia>(0);
     private Set<PonderaCopia> ponderaCopias = new HashSet<PonderaCopia>(0);

    public PreguntaCopia() {
    }

	
    public PreguntaCopia(int idPreguntaCopia) {
        this.idPreguntaCopia = idPreguntaCopia;
    }
    public PreguntaCopia(int idPreguntaCopia, FactorCopia factorCopia, OpcionRespuestaCopia opcionRespuestaCopia, String nombrePregunta, String pregunta, String descripcion, Set<CuestionarioPreguntaCopia> cuestionarioPreguntaCopias, Set<PonderaCopia> ponderaCopias) {
       this.idPreguntaCopia = idPreguntaCopia;
       this.factorCopia = factorCopia;
       this.opcionRespuestaCopia = opcionRespuestaCopia;
       this.nombrePregunta = nombrePregunta;
       this.pregunta = pregunta;
       this.descripcion = descripcion;
       this.cuestionarioPreguntaCopias = cuestionarioPreguntaCopias;
       this.ponderaCopias = ponderaCopias;
    }
   
    public int getIdPreguntaCopia() {
        return this.idPreguntaCopia;
    }
    
    public void setIdPreguntaCopia(int idPreguntaCopia) {
        this.idPreguntaCopia = idPreguntaCopia;
    }
    public FactorCopia getFactorCopia() {
        return this.factorCopia;
    }
    
    public void setFactorCopia(FactorCopia factorCopia) {
        this.factorCopia = factorCopia;
    }
    public OpcionRespuestaCopia getOpcionRespuestaCopia() {
        return this.opcionRespuestaCopia;
    }
    
    public void setOpcionRespuestaCopia(OpcionRespuestaCopia opcionRespuestaCopia) {
        this.opcionRespuestaCopia = opcionRespuestaCopia;
    }
    public String getNombrePregunta() {
        return this.nombrePregunta;
    }
    
    public void setNombrePregunta(String nombrePregunta) {
        this.nombrePregunta = nombrePregunta;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<CuestionarioPreguntaCopia> getCuestionarioPreguntaCopias() {
        return this.cuestionarioPreguntaCopias;
    }
    
    public void setCuestionarioPreguntaCopias(Set<CuestionarioPreguntaCopia> cuestionarioPreguntaCopias) {
        this.cuestionarioPreguntaCopias = cuestionarioPreguntaCopias;
    }
    public Set<PonderaCopia> getPonderaCopias() {
        return this.ponderaCopias;
    }
    
    public void setPonderaCopias(Set<PonderaCopia> ponderaCopias) {
        this.ponderaCopias = ponderaCopias;
    }




}


