package Entidades;
// Generated 16/09/2016 18:42:16 by Hibernate Tools 4.3.1



/**
 * PuestoCompetenciaId generated by hbm2java
 */
public class PuestoCompetenciaId  implements java.io.Serializable {


     private int idPuesto;
     private int idCompetencia;

    public PuestoCompetenciaId() {
    }

    public PuestoCompetenciaId(int idPuesto, int idCompetencia) {
       this.idPuesto = idPuesto;
       this.idCompetencia = idCompetencia;
    }
   
    public int getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(int idPuesto) {
        this.idPuesto = idPuesto;
    }
    public int getIdCompetencia() {
        return this.idCompetencia;
    }
    
    public void setIdCompetencia(int idCompetencia) {
        this.idCompetencia = idCompetencia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PuestoCompetenciaId) ) return false;
		 PuestoCompetenciaId castOther = ( PuestoCompetenciaId ) other; 
         
		 return (this.getIdPuesto()==castOther.getIdPuesto())
 && (this.getIdCompetencia()==castOther.getIdCompetencia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPuesto();
         result = 37 * result + this.getIdCompetencia();
         return result;
   }   


}


