package Entidades;
// Generated 14/11/2016 15:56:53 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PuestoCopia generated by hbm2java
 */
public class PuestoCopia  implements java.io.Serializable {


     private int idPuestoCopia;
     private Puesto puestoOriginal;
     private String nombreEmpresa;
     private Date fechaCopia;
     private String nombrePuesto;
     private String descripcion;
     private Set competencias = new HashSet(0);

    public PuestoCopia() {
    }

	
    public PuestoCopia(int idPuestoCopia) {
        this.idPuestoCopia = idPuestoCopia;
    }
    public PuestoCopia(int idPuestoCopia, Puesto puestoOriginal, String nombreEmpresa, Date fechaCopia, String nombrePuesto, String descripcion, Set competencias) {
       this.idPuestoCopia = idPuestoCopia;
       this.puestoOriginal = puestoOriginal;
       this.nombreEmpresa = nombreEmpresa;
       this.fechaCopia = fechaCopia;
       this.nombrePuesto = nombrePuesto;
       this.descripcion= descripcion;
       this.competencias=competencias;
    }
   
    public int getIdPuestoCopia() {
        return this.idPuestoCopia;
    }
    
    public void setIdPuestoCopia(int idPuestoCopia) {
        this.idPuestoCopia = idPuestoCopia;
    }
    public Puesto getPuestoOriginal() {
        return this.puestoOriginal;
    }
    
    public void setPuestoOriginal(Puesto puestoOriginal) {
        this.puestoOriginal = puestoOriginal;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public Date getFechaCopia() {
        return this.fechaCopia;
    }
    
    public void setFechaCopia(Date fechaCopia) {
        this.fechaCopia = fechaCopia;
    }
    public String getNombrePuesto() {
        return this.nombrePuesto;
    }
    
    public void setNombrePuesto(String nombrePuesto) {
        this.nombrePuesto = nombrePuesto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCompetencias() {
        return this.competencias;
    }
    
    public void setCompetencias(Set competencias) {
        this.competencias = competencias;
    }
}


