package Entidades;
// Generated 11/09/2016 22:33:21 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private int idPuesto;
     private String nombrePuesto;
     private String nombreEmpresa;
     private Date fechaUltMod;
     private List<Competencia> competencias = new ArrayList<Competencia>();

    public Puesto() {
    }

	
    public Puesto(int idPuesto) {
        this.idPuesto = idPuesto;
    }
    public Puesto(int idPuesto, String nombrePuesto, String nombreEmpresa, Date fechaUltMod) {
       this.idPuesto = idPuesto;
       this.nombrePuesto = nombrePuesto;
       this.nombreEmpresa = nombreEmpresa;
       this.fechaUltMod = fechaUltMod;
    }
   
    public int getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(int idPuesto) {
        this.idPuesto = idPuesto;
    }
    public String getNombrePuesto() {
        return this.nombrePuesto;
    }
    
    public void setNombrePuesto(String nombrePuesto) {
        this.nombrePuesto = nombrePuesto;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public Date getFechaUltMod() {
        return this.fechaUltMod;
    }
    
    public void setFechaUltMod(Date fechaUltMod) {
        this.fechaUltMod = fechaUltMod;
    }
    
     public List<Competencia> getCompetencias()
    {
        return competencias;
    }

    private void setCompetencias(List<Competencia> competencias)
    {
        this.competencias = competencias;
    }
    
    public void addCompetencia(Competencia competencia)
    {
        this.competencias.add(competencia);
    }

}


