package Entidades;
// Generated 05-sep-2016 13:10:58 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private int idPuesto;
     private String nombrePuesto;
     private String nombreEmpresa;
     private Date fechaUltMod;

    public Puesto() {
    }

	
    public Puesto(int idPuesto) {
        this.idPuesto = idPuesto;
    }
    public Puesto(int idPuesto, String nombrePuesto, String nombreEmpresa, Date fechaUltMod) {
       this.idPuesto = idPuesto;
       this.nombrePuesto = nombrePuesto;
       this.nombreEmpresa = nombreEmpresa;
       this.fechaUltMod = fechaUltMod;
    }
   
    public int getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(int idPuesto) {
        this.idPuesto = idPuesto;
    }
    public String getNombrePuesto() {
        return this.nombrePuesto;
    }
    
    public void setNombrePuesto(String nombrePuesto) {
        this.nombrePuesto = nombrePuesto;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public Date getFechaUltMod() {
        return this.fechaUltMod;
    }
    
    public void setFechaUltMod(Date fechaUltMod) {
        this.fechaUltMod = fechaUltMod;
    }




}


