package Entidades;
// Generated 06-dic-2016 15:03:43 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RaCuestionario generated by hbm2java
 */
public class RaCuestionario  implements java.io.Serializable {


     private int idRaCuestionario;
     private Cuestionario cuestionario;
     private Integer estadoActual;
     private Integer estadoPrevio;
     private Date fecha;

    public RaCuestionario() {
    }

	
    public RaCuestionario(int idRaCuestionario) {
        this.idRaCuestionario = idRaCuestionario;
    }
    public RaCuestionario(int idRaCuestionario, Cuestionario cuestionario, Integer estadoActual, Integer estadoPrevio, Date fecha) {
       this.idRaCuestionario = idRaCuestionario;
       this.cuestionario = cuestionario;
       this.estadoActual = estadoActual;
       this.estadoPrevio = estadoPrevio;
       this.fecha = fecha;
    }
   
    public int getIdRaCuestionario() {
        return this.idRaCuestionario;
    }
    
    public void setIdRaCuestionario(int idRaCuestionario) {
        this.idRaCuestionario = idRaCuestionario;
    }
    public Cuestionario getCuestionario() {
        return this.cuestionario;
    }
    
    public void setCuestionario(Cuestionario cuestionario) {
        this.cuestionario = cuestionario;
    }
    public Integer getEstadoActual() {
        return this.estadoActual;
    }
    
    public void setEstadoActual(Integer estadoActual) {
        this.estadoActual = estadoActual;
    }
    public Integer getEstadoPrevio() {
        return this.estadoPrevio;
    }
    
    public void setEstadoPrevio(Integer estadoPrevio) {
        this.estadoPrevio = estadoPrevio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


