package Entidades;
// Generated 06-dic-2016 15:03:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RespuestaCopia generated by hbm2java
 */
public class RespuestaCopia  implements java.io.Serializable {


     private int idRespuestaCopia;
     private OpcionRespuestaCopia opcionRespuestaCopia;
     private String respuesta;
     private Set<CuestionarioRespuestaCopia> cuestionarioRespuestaCopias = new HashSet<CuestionarioRespuestaCopia>(0);
     private Set<PonderaCopia> ponderaCopias = new HashSet<PonderaCopia>(0);

    public RespuestaCopia() {
    }

	
    public RespuestaCopia(int idRespuestaCopia) {
        this.idRespuestaCopia = idRespuestaCopia;
    }
    public RespuestaCopia(int idRespuestaCopia, OpcionRespuestaCopia opcionRespuestaCopia, String respuesta, Set<CuestionarioRespuestaCopia> cuestionarioRespuestaCopias, Set<PonderaCopia> ponderaCopias) {
       this.idRespuestaCopia = idRespuestaCopia;
       this.opcionRespuestaCopia = opcionRespuestaCopia;
       this.respuesta = respuesta;
       this.cuestionarioRespuestaCopias = cuestionarioRespuestaCopias;
       this.ponderaCopias = ponderaCopias;
    }
   
    public int getIdRespuestaCopia() {
        return this.idRespuestaCopia;
    }
    
    public void setIdRespuestaCopia(int idRespuestaCopia) {
        this.idRespuestaCopia = idRespuestaCopia;
    }
    public OpcionRespuestaCopia getOpcionRespuestaCopia() {
        return this.opcionRespuestaCopia;
    }
    
    public void setOpcionRespuestaCopia(OpcionRespuestaCopia opcionRespuestaCopia) {
        this.opcionRespuestaCopia = opcionRespuestaCopia;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public Set<CuestionarioRespuestaCopia> getCuestionarioRespuestaCopias() {
        return this.cuestionarioRespuestaCopias;
    }
    
    public void setCuestionarioRespuestaCopias(Set<CuestionarioRespuestaCopia> cuestionarioRespuestaCopias) {
        this.cuestionarioRespuestaCopias = cuestionarioRespuestaCopias;
    }
    public Set<PonderaCopia> getPonderaCopias() {
        return this.ponderaCopias;
    }
    
    public void setPonderaCopias(Set<PonderaCopia> ponderaCopias) {
        this.ponderaCopias = ponderaCopias;
    }




}


